### ISSUE TITLE
菜单Menu怎么配置

### ISSUE THREAD

**Issue by Gznq** [sail-sail/reuse-tab#1]
请问菜单怎么配置？

**Comment by sail-sail** [comment]
看说明文档, 菜单只是路由跳转而已, 你做好angular的路由

**Comment by sail-sail** [comment]
例如: 
`<a routerLink="/usr" routerLinkActive="menu_active" class="menu_item">账户列表</a>
<a routerLink="/login_log" routerLinkActive="menu_active" class="menu_item">登录日志</a>
<a routerLink="/option" routerLinkActive="menu_active" class="menu_item">系统选项</a>`

**Comment by Gznq** [comment]
> 文档中说按菜单'menu'配置如：{ text:'Dashboard', reuse: false } ，这是添加在哪呢？

需要导入其他扫描服务吗？

**Comment by sail-sail** [comment]
路由啊，路由那里除了配置路径，加上这些选项
