### ISSUE TITLE
默认无法复用？

### ISSUE THREAD

**Issue by Nongzhsh** [sail-sail/reuse-tab#2]
默认好像无法复用，需要手动在路由data中设置reuse，如： { title:'Dashboard', reuse: true }；
鼠标右键无效，没有右键菜单的效果；
切换标签页时激活状态无效，没有下划线的效果；

**Comment by sail-sail** [comment]
默认是不复用的, 设置了 reuse: true, 才复用路由

**Comment by Nongzhsh** [comment]
这样啊，有什么快捷的配置吗，菜单比较多……

**Comment by Nongzhsh** [comment]
已经全部搞定了

**Comment by sail-sail** [comment]
可以了, 现在1.1.0版本, 默认是复用的了
